#pragma once
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include "rp2040/rp2040.h"

#define RESETS_RESET_MASK 0x1FFFFFF
#define RESETS_RESET      ((volatile uint32_t*)(RESETS_BASE + RESETS_RESET_OFFSET))
#define RESETS_RESET_DONE ((volatile uint32_t*)(RESETS_BASE + RESETS_RESET_DONE_OFFSET))

// --- Reset subsystem bit definitions ---
typedef enum
{
  RESETS_RESET_ADC = 1 << RESETS_RESET_ADC_OFFSET,
  RESETS_RESET_BUSCTRL = 1 << RESETS_RESET_BUSCTRL_OFFSET,
  RESETS_RESET_DMA = 1 << RESETS_RESET_DMA_OFFSET,
  RESETS_RESET_I2C0 = 1 << RESETS_RESET_I2C0_OFFSET,
  RESETS_RESET_I2C1 = 1 << RESETS_RESET_I2C1_OFFSET,
  RESETS_RESET_IO_BANK0 = 1 << RESETS_RESET_IO_BANK0_OFFSET,
  RESETS_RESET_IO_QSPI = 1 << RESETS_RESET_IO_QSPI_OFFSET,
  RESETS_RESET_JTAG = 1 << RESETS_RESET_JTAG_OFFSET,
  RESETS_RESET_PADS_BANK0 = 1 << RESETS_RESET_PADS_BANK0_OFFSET,
  RESETS_RESET_PADS_QSPI = 1 << RESETS_RESET_PADS_QSPI_OFFSET,
  RESETS_RESET_PIO0 = 1 << RESETS_RESET_PIO0_OFFSET,
  RESETS_RESET_PIO1 = 1 << RESETS_RESET_PIO1_OFFSET,
  RESETS_RESET_PLL_SYS = 1 << RESETS_RESET_PLL_SYS_OFFSET,
  RESETS_RESET_PLL_USB = 1 << RESETS_RESET_PLL_USB_OFFSET,
  RESETS_RESET_PWM = 1 << RESETS_RESET_PWM_OFFSET,
  RESETS_RESET_RTC= 1 << RESETS_RESET_RTC_OFFSET,
  RESETS_RESET_SPI0 = 1 << RESETS_RESET_SPI0_OFFSET,
  RESETS_RESET_SPI1 = 1 << RESETS_RESET_SPI1_OFFSET,
  RESETS_RESET_SYSCFG = 1 << RESETS_RESET_SYSCFG_OFFSET,
  RESETS_RESET_SYSINFO = 1 << RESETS_RESET_SYSINFO_OFFSET,
  RESETS_RESET_TBMAN = 1 << RESETS_RESET_TBMAN_OFFSET,
  RESETS_RESET_TIMER = 1 << RESETS_RESET_TIMER_OFFSET,
  RESETS_RESET_UART0 = 1 << RESETS_RESET_UART0_OFFSET,
  RESETS_RESET_UART1 = 1 << RESETS_RESET_UART1_OFFSET,
  RESETS_RESET_USBCTRL = 1 << RESETS_RESET_USBCTRL_OFFSET
} reset_subsystem_enum;

// --- Reset one or more subsystems ---
// Asserts and de-asserts reset for the requested subsystems and waits
// until the reset completion is confirmed.
static inline void reset(uint32_t const subsystems)
{
  uint32_t const value = subsystems & RESETS_RESET_MASK;

  *RESETS_RESET |= value; // assert reset
  *RESETS_RESET &= ~value; // de-assert reset

  while ((((*RESETS_RESET_DONE) | RESETS_RESET_UART0 | RESETS_RESET_UART1) & value) != value)
  {
  }
}

#ifdef __cplusplus
}
#endif
