#pragma once
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

// --- RESETS peripheral registers (from RP2040 SVD) ---
#define RESETS_BASE 0X4000C000
#define RESETS_RESET_OFFSET 0X0000
#define RESETS_RESET_DONE_OFFSET 0X0008
#define RESETS_RESET_ADC_OFFSET 0
#define RESETS_RESET_BUSCTRL_OFFSET 1
#define RESETS_RESET_DMA_OFFSET 2
#define RESETS_RESET_I2C0_OFFSET 3
#define RESETS_RESET_I2C1_OFFSET 4
#define RESETS_RESET_IO_BANK0_OFFSET 5
#define RESETS_RESET_IO_QSPI_OFFSET 6
#define RESETS_RESET_JTAG_OFFSET 7
#define RESETS_RESET_PADS_BANK0_OFFSET 8
#define RESETS_RESET_PADS_QSPI_OFFSET 9
#define RESETS_RESET_PIO0_OFFSET 10
#define RESETS_RESET_PIO1_OFFSET 11
#define RESETS_RESET_PLL_SYS_OFFSET 12
#define RESETS_RESET_PLL_USB_OFFSET 13
#define RESETS_RESET_PWM_OFFSET 14
#define RESETS_RESET_RTC_OFFSET 15
#define RESETS_RESET_SPI0_OFFSET 16
#define RESETS_RESET_SPI1_OFFSET 17
#define RESETS_RESET_SYSCFG_OFFSET 18
#define RESETS_RESET_SYSINFO_OFFSET 19
#define RESETS_RESET_TBMAN_OFFSET 20
#define RESETS_RESET_TIMER_OFFSET 21
#define RESETS_RESET_UART0_OFFSET 22
#define RESETS_RESET_UART1_OFFSET 23
#define RESETS_RESET_USBCTRL_OFFSET 24

#define RESETS_RESET_MASK 0x1FFFFFF
#define RESETS_RESET      ((volatile uint32_t*)(RESETS_BASE + RESETS_RESET_OFFSET))
#define RESETS_RESET_DONE ((volatile uint32_t*)(RESETS_BASE + RESETS_RESET_DONE_OFFSET))

// --- Reset subsystem bit definitions ---
typedef enum
{
  RESETS_RESET_ADC = 1 << RESETS_RESET_ADC_OFFSET,
  RESETS_RESET_BUSCTRL = 1 << RESETS_RESET_BUSCTRL_OFFSET,
  RESETS_RESET_DMA = 1 << RESETS_RESET_DMA_OFFSET,
  RESETS_RESET_I2C0 = 1 << RESETS_RESET_I2C0_OFFSET,
  RESETS_RESET_I2C1 = 1 << RESETS_RESET_I2C1_OFFSET,
  RESETS_RESET_IO_BANK0 = 1 << RESETS_RESET_IO_BANK0_OFFSET,
  RESETS_RESET_IO_QSPI = 1 << RESETS_RESET_IO_QSPI_OFFSET,
  RESETS_RESET_JTAG = 1 << RESETS_RESET_JTAG_OFFSET,
  RESETS_RESET_PADS_BANK0 = 1 << RESETS_RESET_PADS_BANK0_OFFSET,
  RESETS_RESET_PADS_QSPI = 1 << RESETS_RESET_PADS_QSPI_OFFSET,
  RESETS_RESET_PIO0 = 1 << RESETS_RESET_PIO0_OFFSET,
  RESETS_RESET_PIO1 = 1 << RESETS_RESET_PIO1_OFFSET,
  RESETS_RESET_PLL_SYS = 1 << RESETS_RESET_PLL_SYS_OFFSET,
  RESETS_RESET_PLL_USB = 1 << RESETS_RESET_PLL_USB_OFFSET,
  RESETS_RESET_PWM = 1 << RESETS_RESET_PWM_OFFSET,
  RESETS_RESET_RTC= 1 << RESETS_RESET_RTC_OFFSET,
  RESETS_RESET_SPI0 = 1 << RESETS_RESET_SPI0_OFFSET,
  RESETS_RESET_SPI1 = 1 << RESETS_RESET_SPI1_OFFSET,
  RESETS_RESET_SYSCFG = 1 << RESETS_RESET_SYSCFG_OFFSET,
  RESETS_RESET_SYSINFO = 1 << RESETS_RESET_SYSINFO_OFFSET,
  RESETS_RESET_TBMAN = 1 << RESETS_RESET_TBMAN_OFFSET,
  RESETS_RESET_TIMER = 1 << RESETS_RESET_TIMER_OFFSET,
  RESETS_RESET_UART0 = 1 << RESETS_RESET_UART0_OFFSET,
  RESETS_RESET_UART1 = 1 << RESETS_RESET_UART1_OFFSET,
  RESETS_RESET_USBCTRL = 1 << RESETS_RESET_USBCTRL_OFFSET
} reset_subsystem_enum;

// --- Reset one or more subsystems ---
// Asserts and de-asserts reset for the requested subsystems and waits
// until the reset completion is confirmed.
static inline void reset(uint32_t const subsystems)
{
  uint32_t const value = subsystems & RESETS_RESET_MASK;

  REG_WRITE(RESETS_RESET, REG_READ(RESETS_RESET) | value); // assert reset
  REG_WRITE(RESETS_RESET, REG_READ(RESETS_RESET) & ~value); // de-assert reset

  while (((REG_READ(RESETS_RESET_DONE) | RESETS_RESET_UART0 | RESETS_RESET_UART1) & value) != value)
  {
    __asm volatile ("nop");
  }
}

#ifdef __cplusplus
}
#endif
