#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdarg.h>

/**
 * @defgroup util Util
 * @{
 */

/**
 * @defgroup log Log
 * @ingroup util
 * @brief Lightweight and portable logging framework with customizable printers and output targets.
 *
 * The logging module provides a simple and extensible logging system suitable
 * for embedded and desktop environments.
 *
 * It separates **message generation** from **message formatting/output**:
 * - The logging API generates messages with severity and source location metadata.
 * - The **printer** controls how messages are formatted (e.g., level, timestamp, file, line).
 * - The **output** determines where messages are written (e.g., `stdout`, file, UART).
 *
 * By default, messages are processed by ::log_default_printer
 * and written to ::stdout.
 *
 * Example:
 * @code
 * log_set_min_level(LOG_LEVEL_INFO);
 * log_set_printer(log_default_printer);
 * log_set_output(stdout);
 *
 * log_info("System initialized with version %d", version);
 * @endcode
 *
 * @{
 */

/**
 * @brief Logging severity levels.
 */
typedef enum
{
  LOG_DISABLED = -1,       /**< Logging disabled */
  LOG_LEVEL_FATAL = 0,     /**< Critical or fatal errors */
  LOG_LEVEL_ERROR,         /**< Recoverable errors */
  LOG_LEVEL_WARN,          /**< Recoverable warnings */
  LOG_LEVEL_INFO,          /**< Informational messages */
  LOG_LEVEL_DEBUG,         /**< Verbose debug details */
} log_level_t;

/**
 * @brief Function type for log printers.
 *
 * A printer converts a log message and its metadata into human-readable text
 * and writes it to the configured output stream.
 *
 * The metadata includes the source file and line number where the log call
 * originated.
 *
 * Example output:
 * @code
 * [INFO] uart.c:142 Transmission complete
 * @endcode
 *
 * @param output Output stream where the message should be written.
 * @param level  Log severity level.
 * @param file   Source file name generated by the compiler (`__FILE__`).
 * @param line   Source line number where the log call occurred.
 * @param fmt    printf-style format string.
 * @param args   Arguments corresponding to the format string.
 *
 * @note Custom printers should be thread-safe and reentrant.
 * @note Printers may be called from any context (thread or ISR).
 */
typedef void (*log_printer_func_t)(FILE* output, log_level_t level, char const* file, int line, char const* fmt, va_list args);

/**
 * @brief Configure the output stream.
 *
 * Defines the destination for all log messages.
 * Defaults to ::stdout.
 *
 * This can be redirected to a file or a custom `FILE*` implementation
 * such as a UART backend.
 *
 * @param output Output stream.
 *
 * @note Configure during initialization.
 * @warning Do not call while other threads are logging.
 */
void log_set_output(FILE* output);

/**
 * @brief Set the minimum log level.
 *
 * Messages below this level are ignored.
 *
 * The default level is ::LOG_LEVEL_INFO.
 *
 * @param level Minimum severity level to output.
 *
 * @note Configure during initialization.
 */
void log_set_min_level(log_level_t level);

/**
 * @brief Set the active log printer.
 *
 * Defines how log messages are formatted and written.
 *
 * @param printer_func Printer function.
 *
 * Example:
 * @code
 * log_set_printer(log_default_printer);
 * @endcode
 *
 * @note Configure during initialization.
 */
void log_set_printer(log_printer_func_t printer_func);

/**
 * @brief Prints a formatted log message with severity and source location.
 *
 * This function is normally called through the convenience macros:
 * ::log_fatal, ::log_error, ::log_warn, ::log_info, and ::log_debug.
 *
 * @param level Log severity level.
 * @param file  Source file name (`__FILE__`).
 * @param line  Source line number (`__LINE__`).
 * @param fmt   printf-style format string.
 * @param ...   Format arguments.
 *
 * @note Messages below the configured minimum level are ignored.
 */
void log_print(log_level_t level, char const* file, int line, char const* fmt, ...);

/**
 * @brief Prints a fatal error message.
 *
 * Automatically includes source file and line information.
 *
 * @param fmt Format string.
 * @param ... Format arguments.
 */
#define log_fatal(fmt, ...) log_print(LOG_LEVEL_FATAL, __FILE__, __LINE__, fmt, ##__VA_ARGS__)

/**
 * @brief Prints an error message.
 *
 * Automatically includes source file and line information.
 *
 * @param fmt Format string.
 * @param ... Format arguments.
 */
#define log_error(fmt, ...) log_print(LOG_LEVEL_ERROR, __FILE__, __LINE__, fmt, ##__VA_ARGS__)

/**
 * @brief Prints a warning message.
 *
 * Automatically includes source file and line information.
 *
 * @param fmt Format string.
 * @param ... Format arguments.
 */
#define log_warn(fmt, ...) log_print(LOG_LEVEL_WARN, __FILE__, __LINE__, fmt, ##__VA_ARGS__)

/**
 * @brief Prints an informational message.
 *
 * Automatically includes source file and line information.
 *
 * @param fmt Format string.
 * @param ... Format arguments.
 */
#define log_info(fmt, ...) log_print(LOG_LEVEL_INFO, __FILE__, __LINE__, fmt, ##__VA_ARGS__)

/**
 * @brief Prints a debug message.
 *
 * Automatically includes source file and line information.
 *
 * @param fmt Format string.
 * @param ... Format arguments.
 *
 * @note Debug messages are usually enabled only for debug builds.
 */
#define log_debug(fmt, ...) log_print(LOG_LEVEL_DEBUG, __FILE__, __LINE__, fmt, ##__VA_ARGS__)

/**
 * @brief Default human-readable log printer.
 *
 * Produces output in the following format:
 *
 * @code
 * [LEVEL] file:line message
 * @endcode
 *
 * Example:
 *
 * @code
 * [ERROR] scheduler.c:87 Failed to create idle thread
 * @endcode
 *
 * @param output Output stream.
 * @param level  Log severity level.
 * @param file   Source file name.
 * @param line   Source line number.
 * @param fmt    printf-style format string.
 * @param args   Format arguments.
 *
 * @note Thread-safe; safe to use as a log printer function.
 */
void log_default_printer(FILE* output, log_level_t level, char const* file, int line, char const* fmt, va_list args);

/** @} */ /* end of log group */

/** @} */ /* end of util group */

#ifdef __cplusplus
}
#endif